### ISSUE TITLE
60 minutes

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mycroft-timer#6]
Testing https://github.com/MycroftAI/mycroft-core/issues/911 I noticed that the skill doesn't accept 60 minutes as a time. Instead it fails silently.

The exception `ValueError: minute must be in 0..59` is logged.

Since a user uses this wording (and it's not too strange really) I think it should be supported.

**Comment by penrods** [comment]
Partially dealt with in #3  -- the old parser used wouldn't take "invalid" things like minutes or seconds > 60.  The new method doesn't allow mixing units, such as "set a timer for 1 minute and 30 seconds", so that will need to be added to the Mycroft parsing (but at least we are in control of that code).

**Comment by MatthewScholefield** [comment]
This worked for me. Closing.
